apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kb-class-storage
  resources:
    requests:
      storage: 500Mi