apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
  namespace: homework
  labels:
    app: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: mynginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080