apiVersion: v1
kind: ConfigMap
metadata:
  namespace: homework
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 8000 default_server;
      listen [::]:8000 default_server;
      root /homework;
      index index.html
      server_name _;
      location / {
        try_files $uri $uri/ =404;
      }
    }
---