
apiVersion: v1
kind: Pod
metadata:
  namespace: homework
  labels:
    type: webserver
  name: nginx
spec:
  initContainers:
  - name: init
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - www.stackoverflow.com
    volumeMounts:
    - mountPath: /init
      name: volume-shared

  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - mountPath: /homework
      name: volume-shared
      
    - mountPath: /etc/nginx/conf.d 
      readOnly: true
      name: nginx-conf

  dnsPolicy: Default

  volumes:
  - name: volume-shared
    emptyDir: {}

  - name: nginx-conf
    configMap:
      name: nginx-conf 
      items:
        - key: nginx.conf
          path: nginx.conf

        