apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter-deployment
  namespace: homework
  labels:
    app: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-exporter
  template:
    metadata:
      labels:
        app: prometheus-exporter
    spec:
      containers:
      - name: prometheus-exporter
        image: nginx/nginx-prometheus-exporter:latest
        ports:
        - containerPort: 9113
          name: metrics
        args:
          - --nginx.scrape-uri=http://mynginx-service:80/nginx_status