apiVersion: v1
kind: Service
metadata:
  name: prometheus-exporter-service
  namespace: homework
  labels:
    app: prometheus-exporter-service
    app.kubernetes.io/name: prometheus-exporter-service
    app.kubernetes.io/instance: prometheus-exporter-service
spec:
  selector:
    app: prometheus-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: metrics