apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: sa-crd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments",]
  verbs: ["get", "create", "delete"]

- apiGroups: ["apps"] # for gettting replica's status
  resources: ["deployments/status"] 
  verbs: ["get"]

- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "persistentvolumes"] 
  verbs: ["create", "delete"]

- apiGroups: [""] #to post logs
  resources: ["events"]
  verbs: ["create"]

- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["create", "list", "get", "watch","delete", "patch", "update"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-role-binding
subjects:
- kind: ServiceAccount
  name: sa-crd
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-role
  apiGroup: rbac.authorization.k8s.io