apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: sa-crd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments","deployments/status"]
  verbs: ["get", "watch", "create", "delete", "get", "list", "update"]

- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "persistentvolumes", "events"]
  verbs: ["create", "update", "delete", "get", "list", "watch"]

- apiGroups: ["otus.homework"]
  resources: ["mysqls"]
  verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-role-binding
subjects:
- kind: ServiceAccount
  name: sa-crd
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-role
  apiGroup: rbac.authorization.k8s.io