apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: sa-crd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-role
rules:
- apiGroups: ["", "apps", "otus.homework", "apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-role-binding
subjects:
- kind: ServiceAccount
  name: sa-crd
  namespace: default
roleRef:
  kind: ClusterRole
  name: crd-role
  apiGroup: rbac.authorization.k8s.io