apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  names:
    plural: mysqls
    singular: mysql
    kind: MySql
    shortNames:
    - mysql
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          # metadata:
          #   type: object
          #   properties:
          #     name:
          #       type: string
          #       minLength: 1
          #     namespace:
          #       type: string
          #       minLength: 1
          #   required:
          #   - name
          #   - namespace
          spec:
            type: object
            properties:
              image:
                type: string
                minLength: 1
              database:
                type: string
                minLength: 1
              password:
                type: string
                minLength: 1
              storage_size:
                type: string
                minLength: 1
            required:
            - image
            - database
            - password
            - storage_size

  scope: Namespaced
  
        