apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.persistentVolumeClaim.name  }}
  namespace: {{ include "renapp.namespace" . }}
  labels:
  {{- include "renapp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.persistentVolumeClaim.storage }}
