apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-homework
  namespace: homework
data:
  nginx.conf: |
    server {
      listen 8000;
      root /homework;
      index index.html;
      location / {
        try_files $uri $uri/ /index.html;     
      }
      location /metrics {
        try_files $uri $uri/ /metrics.html;     
      }
    }
  homework-conf: |
    hello, I'am a configMap