apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-secret
  namespace: vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: otus-cred
  data:
    - secretKey: pass
      remoteRef:
        key: cred 
        property: password 
    - secretKey: user
      remoteRef:
        key: cred  
        property: username 