apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "otus"
      auth:
        kubernetes:
          role: "otus"
          serviceAccountRef:
            name: vault-auth