apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-networks
  namespace: argo-cd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-02OTUS/renser1998_repo.git
    targetRevision: kubernetes-networks
    path: lesson3
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true